# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - jo: TreeSitter
    displayName: Build TreeSitterJava
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build TreeSitter Parser Image.
      inputs:
        containerRegistry: 'Dockerhub Autosecurity Architect'
        repository: 'senanayake76/autosecurityarchitect'
        command: 'buildAndPush'
        Dockerfile: 'BuildTreeSitterParser/Dockerfile'
        tags: |
          treesitter  