# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: BuildJava11
    displayName: Build Java 11 image
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build Java 11 image
      inputs:
        containerRegistry: 'Dockerhub Autosecurity Architect'
        repository: 'senanayake76/autosecurityarchitect'
        command: 'buildAndPush'
        Dockerfile: 'TestJavaBuild/Java11Build/Dockerfile'
        tags: |
          $(tag)-java11
  - job: BuildJava17
    displayName: Build Java 17 image
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build Java 17 image
      inputs:
        containerRegistry: 'Dockerhub Autosecurity Architect'
        repository: 'senanayake76/autosecurityarchitect'
        command: 'buildAndPush'
        Dockerfile: 'TestJavaBuild/Java17Build/Dockerfile'
        tags: |
          $(tag)-java17          
  - job: TreeSitter
    displayName: Build TreeSitterJava
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build TreeSitter Parser Image.
      inputs:
        containerRegistry: 'Dockerhub Autosecurity Architect'
        repository: 'senanayake76/autosecurityarchitect'
        command: 'buildAndPush'
        Dockerfile: 'BuildTreeSitterParser/Dockerfile'
        tags: |
          $(tag)-treesitter  